### ISSUE TITLE
Template issue in Chrome

### ISSUE THREAD

**Issue by DjingoDjango** [mblayman/markwiki#24]
Hi

First off; Your MarkWiki concept is great! Just what we were looking for; a dead simple elegant wiki that can be edited easily. So, thank you for laboring this into existence!

There was one smaller issue I ran into in Chrome; The search bar disappears behind the bread crumbs graphics. The Edit button is suffering from a similar issue as it disappears behind the wiki page title. Please see the screen dump below.

![markwiki search bar](https://cloud.githubusercontent.com/assets/8713774/7258954/2a23c07c-e860-11e4-90fc-5447c400ca39.jpg)

The same is not true for IE. as opposed to Chrome, the search bar and edit button is fixed to the page, in contrast to the Chrome rendering where the two objects are fixed to the nav-bar, resulting in the two elements hiding behind the text that scrolls past. 

I am using, what I think is the latest Chrome version; 42.0.2311.90 m

Also; Are you sure you want the edit button on the top of the page? I definitely get why the search bar is at the top, but the edit button is taking focus away from the Wiki page title.. 

First time I am entering an Issue in GitHub so if I am not complying with the prevailing site etiquette, I do apologize in advance!

I did try to solve the problem myself, but I am basically completely oblivious about bootstrap, so the solutions I tried did not turn out the way I intended. 

EDIT: On second thoughts, this issue might belong to Bootstrap / Chrome rather then to the MarkWiki project??

Anyway, congrats on a thoroughly cool project!

**Comment by mblayman** [comment]
@DjingoDjango thanks for the report! I'm glad that you like MarkWiki and took the time to submit an issue. I've been on holiday for a couple of weeks and totally away from a computer so I apologize for the late response.

I think your comment about Bootstrap is probably correct. I have not updated the Bootstrap version included with MarkWiki in over a year. Including a newer version may fix the problem. I'll see if I can do that in the near future and test it out in Chrome. Once that is done, I can put out a new release.
