### ISSUE TITLE
Make Sections actually work as pages as well

### ISSUE THREAD

**Issue by lu-zero** [mblayman/markwiki#31]
Right now Sections and Pages are different objects making quite confusing navigating back e.g.

Pages:
Security
Security/tools
Security/pitfalls

Sections:
Security

The slug gets you to the Section while a Page would be more intuitive.

**Comment by mblayman** [comment]
Sections were a design choice that I made on purpose. My intention was to permit users to have a namespace where they could view related content (e.g., http://pythonhosted.org/MarkWiki/list/MarkWiki/).

If you think there is a way I can expand the documentation to make sections more clear (http://pythonhosted.org/MarkWiki/wiki/MarkWiki/Features/#wiki-sections), please let me know. I don't want to unify sections and pages into a singular concept.

If I recall correctly, it's possible to have a section and a page with the same name, but I may be remembering that incorrectly. The wiki links to differentiate would be `[[Something/]]` for the section and `[[Something]]` for the page.

**Comment by lu-zero** [comment]
It is possible and makes navigation ultra-confusing (and makes migrating from moin-moin impossible)
